---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postres-pv
  labels:
    type: local
spec:
  storageClassName: mystorage
  accessMode:
    -ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/data/mypostgresdata"
