apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: people
  name: people 
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: people
  template:
    metadata:
      labels:
        app: people
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          name: people

---
apiVersion: v1
kind: Service
metadata:
  name: people
  namespace: default
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: people
