---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
  namespace: prod
spec:
  ports:
  - name: postgres
    port: 5432
  selector:
    app: postrges
  type: ClusterIP
