---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: popovna/app-backend
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@postgres:5432/news
        volumeMounts:
        - name: share
          mountPath: /static
      volumes:
      - name: share
        persistentVolumeClaim:
          claimName: share-volume-claim   
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
  namespace: prod
spec:
  selector:
    app: backend
  ports:
  - name: back
    port: 9000
    targetPort: 9000
