---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-volume-claim
  namespace: prod
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  hostPath:
    path: /data/pv
