---
apiVersion: v1    
kind: PersistentVolumeClaim
metadata:
  name: share-volume-claim
  namespace: prod
spec:
  storageClassName: "nfs"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
