---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: popovna/app-backend
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
  namespace: prod
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - name: back
    port: 9000
